version: '3'

services:
  app-dev:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: local-better-webapp-nextjs
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 80:3000
