/**
 * @typedef {object} GetstreamPost.Actor
 * @property {object} created_at
 * @property {object} updated_at
 * @property {string} id
 * @property {GetstreamPost.Actor.Data} data
 */

/**
 * @typedef {object} GetstreamPost.Actor.Data
 * @property {string} human_id
 * @property {string} profile_pic_url
 * @property {string} username
 */

/**
 * @typedef {object} GetstreamPost.MyPolling
 * @property {string} log_polling_id
 * @property {string} polling_option_id
 * @property {string} polling_id
 * @property {string} user_id
 * @property {string} createdAt
 * @property {string} updatedAt
 * 
 */

/**
 * @typedef {object} GetstreamPost.NewsLink
 * @property {string} date
 * @property {string} description
 * @property {string} domain
 * @property {string} domainImage
 * @property {string} domain_page_id
 * @property {string} image
 * @property {string} news_feed_id
 * @property {string} news_link_id
 * @property {string} title
 * @property {string} url
 */

/**
 * @typedef {object} GetstreamPost
 * @property {GetstreamPost.Actor} actor
 * @property {GetstreamPost.MyPolling} mypolling
 * @property {GetstreamPost.NewsLink} og
 * @property {boolean} anonimity
 * @property {boolean} isalreadypolling
 * @property {boolean} multiplechoice
 * @property {null|string} origin
 * @property {number} count_downvote
 * @property {number} count_upvote
 * @property {number} post_type
 * @property {number} score
 * @property {number} voteCount
 * @property {string[]} polls
 * @property {string[]} topics
 * @property {string|null} expired_at
 * @property {string} duration_feed
 * @property {string} foreign_id
 * @property {string} id
 * @property {string} images_url
 * @property {string} location
 * @property {string} message
 * @property {string} object
 * @property {string} polling_id
 * @property {string} polls_expired_at
 * @property {string} privacy
 * @property {string} target
 * @property {string} time
 * @property {string} verb
 * @property {string} credderScore
 * @property {string} credderLastChecked
 * 
 */


/** 
 * @typedef {object} GetstreamPostResponse
 * @property {number} code
 * @property {string} status
 * @property {object[]} data

 * @property {boolean} data.anonimity
 * @property {number} data.count_downvote
 * @property {number} data.count_upvote
 * @property {string} data.duration_feed
 * @property {string|null} data.expired_at
 * @property {string} data.foreign_id
 * @property {string} data.id
 * @property {|string} data.images_url
 * @property {string} data.location
 * @property {string} data.message
 * @property {string} data.object
 * @property {null|string} data.origin
 * @property {number} data.post_type
 * @property {string} data.privacy
 * @property {number} data.score
 * @property {string} data.target
 * @property {string} data.time
 * @property {|string[]} data.topics
 * @property {string} data.verb
 * @property {boolean} data.multiplechoice
 * @property {string} data.polling_id
 * @property {string[]} data.polls
 * @property {string} data.polls_expired_at
 * 
 * @property {boolean} data.isalreadypolling
 * @property {object[]} data.pollOptions
 * @property {string} data.pollOptions.polling_option_id
 * @property {string} data.pollOptions.polling_id
 * @property {string} data.pollOptions.option
 * @property {string} data.pollOptions.counter
 * @property {string} data.pollOptions.createdAt
 * @property {string} data.pollOptions.updatedAt
 * @property {number} data.voteCount
 * @property {object} data.latest_reactions
 * @property {object[]} data.latest_reactions.comment
 * @property {string} data.latest_reactions.comment.created_at
 * @property {string} data.latest_reactions.comment.updated_at
 * @property {string} data.latest_reactions.comment.id
 * @property {string} data.latest_reactions.comment.user_id
 * @property {object} data.latest_reactions.comment.user
 * @property {string} data.latest_reactions.comment.user.created_at
 * @property {string} data.latest_reactions.comment.user.updated_at
 * @property {string} data.latest_reactions.comment.user.id
 * @property {object} data.latest_reactions.comment.user.data
 * @property {string} data.latest_reactions.comment.user.data.human_id
 * @property {string} data.latest_reactions.comment.user.data.profile_pic_url
 * @property {string} data.latest_reactions.comment.user.data.username
 * @property {string} data.latest_reactions.comment.kind
 * @property {string} data.latest_reactions.comment.activity_id
 * @property {object} data.latest_reactions.comment.data
 * @property {number} data.latest_reactions.comment.data.count_downvote
 * @property {number} data.latest_reactions.comment.data.count_upvote
 * @property {string[]} data.latest_reactions.comment.data.targetFeeds
 * @property {string} data.latest_reactions.comment.data.text
 * @property {string[]} data.latest_reactions.comment.target_feeds
 * @property {string} data.latest_reactions.comment.parent
 * @property {object} data.latest_reactions.comment.latest_children
 * @property {object[]} data.latest_reactions.comment.latest_children.comment
 * @property {string} data.latest_reactions.comment.latest_children.comment.created_at
 * @property {string} data.latest_reactions.comment.latest_children.comment.updated_at
 * @property {string} data.latest_reactions.comment.latest_children.comment.id
 * @property {string} data.latest_reactions.comment.latest_children.comment.user_id
 * @property {object} data.latest_reactions.comment.latest_children.comment.user
 * @property {string} data.latest_reactions.comment.latest_children.comment.user.created_at
 * @property {string} data.latest_reactions.comment.latest_children.comment.user.updated_at
 * @property {string} data.latest_reactions.comment.latest_children.comment.user.id
 * @property {object} data.latest_reactions.comment.latest_children.comment.user.data
 * @property {string} data.latest_reactions.comment.latest_children.comment.user.data.human_id
 * @property {string} data.latest_reactions.comment.latest_children.comment.user.data.profile_pic_url
 * @property {string} data.latest_reactions.comment.latest_children.comment.user.data.username
 * @property {string} data.latest_reactions.comment.latest_children.comment.kind
 * @property {string} data.latest_reactions.comment.latest_children.comment.activity_id
 * @property {object} data.latest_reactions.comment.latest_children.comment.data
 * @property {number} data.latest_reactions.comment.latest_children.comment.data.count_downvote
 * @property {number} data.latest_reactions.comment.latest_children.comment.data.count_upvote
 * @property {boolean} data.latest_reactions.comment.latest_children.comment.data.isNotSeen
 * @property {string} data.latest_reactions.comment.latest_children.comment.data.text
 * @property {string[]} data.latest_reactions.comment.latest_children.comment.target_feeds
 * @property {string} data.latest_reactions.comment.latest_children.comment.parent
 * @property {object} data.latest_reactions.comment.children_counts
 * @property {number} data.latest_reactions.comment.children_counts.comment
 * @property {object[]} data.latest_reactions.downvotes
 * @property {string} data.latest_reactions.downvotes.created_at
 * @property {string} data.latest_reactions.downvotes.updated_at
 * @property {string} data.latest_reactions.downvotes.id
 * @property {string} data.latest_reactions.downvotes.user_id
 * @property {object} data.latest_reactions.downvotes.user
 * @property {string} data.latest_reactions.downvotes.user.created_at
 * @property {string} data.latest_reactions.downvotes.user.updated_at
 * @property {string} data.latest_reactions.downvotes.user.id
 * @property {object} data.latest_reactions.downvotes.user.data
 * @property {string} data.latest_reactions.downvotes.user.data.human_id
 * @property {string} data.latest_reactions.downvotes.user.data.profile_pic_url
 * @property {string} data.latest_reactions.downvotes.user.data.username
 * @property {string} data.latest_reactions.downvotes.kind
 * @property {string} data.latest_reactions.downvotes.activity_id
 * @property {object} data.latest_reactions.downvotes.data
 * @property {number} data.latest_reactions.downvotes.data.count_downvote
 * @property {string} data.latest_reactions.downvotes.data.text
 * @property {string[]} data.latest_reactions.downvotes.target_feeds
 * @property {string} data.latest_reactions.downvotes.parent
 * @property {object} data.latest_reactions_extra
 * @property {object} data.latest_reactions_extra.comment
 * @property {string} data.latest_reactions_extra.comment.next
 * @property {object} data.latest_reactions_extra.downvotes
 * @property {string} data.latest_reactions_extra.downvotes.next
 * @property {object} data.own_reactions
 * @property {object[]} data.own_reactions.comment
 * @property {string} data.own_reactions.comment.created_at
 * @property {string} data.own_reactions.comment.updated_at
 * @property {string} data.own_reactions.comment.id
 * @property {string} data.own_reactions.comment.user_id
 * @property {object} data.own_reactions.comment.user
 * @property {string} data.own_reactions.comment.user.created_at
 * @property {string} data.own_reactions.comment.user.updated_at
 * @property {string} data.own_reactions.comment.user.id
 * @property {object} data.own_reactions.comment.user.data
 * @property {string} data.own_reactions.comment.user.data.human_id
 * @property {string} data.own_reactions.comment.user.data.profile_pic_url
 * @property {string} data.own_reactions.comment.user.data.username
 * @property {string} data.own_reactions.comment.kind
 * @property {string} data.own_reactions.comment.activity_id
 * @property {object} data.own_reactions.comment.data
 * @property {number} data.own_reactions.comment.data.count_downvote
 * @property {number} data.own_reactions.comment.data.count_upvote
 * @property {string[]} data.own_reactions.comment.data.targetFeeds
 * @property {string} data.own_reactions.comment.data.text
 * @property {string[]} data.own_reactions.comment.target_feeds
 * @property {string} data.own_reactions.comment.parent
 * @property {object} data.own_reactions.comment.latest_children
 * @property {object[]} data.own_reactions.comment.latest_children.comment
 * @property {string} data.own_reactions.comment.latest_children.comment.created_at
 * @property {string} data.own_reactions.comment.latest_children.comment.updated_at
 * @property {string} data.own_reactions.comment.latest_children.comment.id
 * @property {string} data.own_reactions.comment.latest_children.comment.user_id
 * @property {object} data.own_reactions.comment.latest_children.comment.user
 * @property {string} data.own_reactions.comment.latest_children.comment.user.created_at
 * @property {string} data.own_reactions.comment.latest_children.comment.user.updated_at
 * @property {string} data.own_reactions.comment.latest_children.comment.user.id
 * @property {object} data.own_reactions.comment.latest_children.comment.user.data
 * @property {string} data.own_reactions.comment.latest_children.comment.user.data.human_id
 * @property {string} data.own_reactions.comment.latest_children.comment.user.data.profile_pic_url
 * @property {string} data.own_reactions.comment.latest_children.comment.user.data.username
 * @property {string} data.own_reactions.comment.latest_children.comment.kind
 * @property {string} data.own_reactions.comment.latest_children.comment.activity_id
 * @property {object} data.own_reactions.comment.latest_children.comment.data
 * @property {number} data.own_reactions.comment.latest_children.comment.data.count_downvote
 * @property {number} data.own_reactions.comment.latest_children.comment.data.count_upvote
 * @property {boolean} data.own_reactions.comment.latest_children.comment.data.isNotSeen
 * @property {string} data.own_reactions.comment.latest_children.comment.data.text
 * @property {string[]} data.own_reactions.comment.latest_children.comment.target_feeds
 * @property {string} data.own_reactions.comment.latest_children.comment.parent
 * @property {object} data.own_reactions.comment.children_counts
 * @property {number} data.own_reactions.comment.children_counts.comment
 * @property {object[]} data.own_reactions.downvotes
 * @property {string} data.own_reactions.downvotes.created_at
 * @property {string} data.own_reactions.downvotes.updated_at
 * @property {string} data.own_reactions.downvotes.id
 * @property {string} data.own_reactions.downvotes.user_id
 * @property {object} data.own_reactions.downvotes.user
 * @property {string} data.own_reactions.downvotes.user.created_at
 * @property {string} data.own_reactions.downvotes.user.updated_at
 * @property {string} data.own_reactions.downvotes.user.id
 * @property {object} data.own_reactions.downvotes.user.data
 * @property {string} data.own_reactions.downvotes.user.data.human_id
 * @property {string} data.own_reactions.downvotes.user.data.profile_pic_url
 * @property {string} data.own_reactions.downvotes.user.data.username
 * @property {string} data.own_reactions.downvotes.kind
 * @property {string} data.own_reactions.downvotes.activity_id
 * @property {object} data.own_reactions.downvotes.data
 * @property {number} data.own_reactions.downvotes.data.count_downvote
 * @property {string} data.own_reactions.downvotes.data.text
 * @property {string[]} data.own_reactions.downvotes.target_feeds
 * @property {string} data.own_reactions.downvotes.parent
 * @property {object} data.reaction_counts
 * @property {number} data.reaction_counts.comment
 * @property {number} data.reaction_counts.downvotes
 * @property {number} data.reaction_counts.upvotes
 * @property {object[]} data.latest_reactions.upvotes
 * @property {string} data.latest_reactions.upvotes.created_at
 * @property {string} data.latest_reactions.upvotes.updated_at
 * @property {string} data.latest_reactions.upvotes.id
 * @property {string} data.latest_reactions.upvotes.user_id
 * @property {object} data.latest_reactions.upvotes.user
 * @property {string} data.latest_reactions.upvotes.user.created_at
 * @property {string} data.latest_reactions.upvotes.user.updated_at
 * @property {string} data.latest_reactions.upvotes.user.id
 * @property {object} data.latest_reactions.upvotes.user.data
 * @property {string} data.latest_reactions.upvotes.user.data.human_id
 * @property {string} data.latest_reactions.upvotes.user.data.profile_pic_url
 * @property {string} data.latest_reactions.upvotes.user.data.username
 * @property {string} data.latest_reactions.upvotes.kind
 * @property {string} data.latest_reactions.upvotes.activity_id
 * @property {object} data.latest_reactions.upvotes.data
 * @property {number} data.latest_reactions.upvotes.data.count_upvote
 * @property {string} data.latest_reactions.upvotes.data.text
 * @property {string[]} data.latest_reactions.upvotes.target_feeds
 * @property {string} data.latest_reactions.upvotes.parent
 * @property {object} data.latest_reactions_extra.upvotes
 * @property {string} data.latest_reactions_extra.upvotes.next
 * @property {object[]} data.own_reactions.upvotes
 * @property {string} data.own_reactions.upvotes.created_at
 * @property {string} data.own_reactions.upvotes.updated_at
 * @property {string} data.own_reactions.upvotes.id
 * @property {string} data.own_reactions.upvotes.user_id
 * @property {object} data.own_reactions.upvotes.user
 * @property {string} data.own_reactions.upvotes.user.created_at
 * @property {string} data.own_reactions.upvotes.user.updated_at
 * @property {string} data.own_reactions.upvotes.user.id
 * @property {object} data.own_reactions.upvotes.user.data
 * @property {string} data.own_reactions.upvotes.user.data.human_id
 * @property {string} data.own_reactions.upvotes.user.data.profile_pic_url
 * @property {string} data.own_reactions.upvotes.user.data.username
 * @property {string} data.own_reactions.upvotes.kind
 * @property {string} data.own_reactions.upvotes.activity_id
 * @property {object} data.own_reactions.upvotes.data
 * @property {number} data.own_reactions.upvotes.data.count_upvote
 * @property {string} data.own_reactions.upvotes.data.text
 * @property {string[]} data.own_reactions.upvotes.target_feeds
 * @property {string} data.own_reactions.upvotes.parent
 * @property {number} offset
 */
